---
language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'

env:
  matrix:
    - FLAGS="--prefer-lowest --prefer-stable"
    - FLAGS=""

before_install:
  - pecl channel-update pecl.php.net
  - pecl config-set preferred_state beta
  - echo yes | pecl upgrade apcu
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  - composer self-update && composer update $FLAGS
  - php -m

services:
  - redis-server

script: ./vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  - bash <(curl -s https://codecov.io/bash)
